version: "3.7"
services:
  "mysql":
    image: "sameersbn/mysql:latest"
    environment:
      - "DB_NAME=db-mysql"
      - "DB_USER=karima"
      - "DB_PASS=karima"
    labels:
      - "SERVICE_NAME=mysql"
    ports:
      - "3306:3306"
    volumes:
      - mysql-db:/var/lib/mysql
volumes:
  mysql-db:

